# Generated by Django 4.2.2 on 2023-06-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
